-- Prospecta CRM - schema for Supabase PostgreSQL
-- Run this file once in the Supabase SQL Editor.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  trade_name text,
  cnpj text,
  website text,
  segment text,
  region integer,
  city text,
  state text,
  address text,
  phone text,
  phone_whatsapp_status text not null default 'UNKNOWN' check (phone_whatsapp_status in ('UNKNOWN', 'YES', 'NO')),
  mobile text,
  mobile_whatsapp_status text not null default 'UNKNOWN' check (mobile_whatsapp_status in ('UNKNOWN', 'YES', 'NO')),
  primary_email text,
  employee_count integer,
  employee_range text,
  company_size text,
  notes text,
  status text not null default 'NOT_CONTACTED' check (status in ('NOT_CONTACTED', 'CONTACTED', 'WAITING_REPLY', 'REPLIED', 'FOLLOW_UP', 'INTERESTED', 'NOT_INTERESTED', 'CLOSED')),
  last_contact_at bigint,
  next_follow_up_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  constraint uq_companies_owner_cnpj unique (owner_id, cnpj)
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text,
  email text,
  phone text,
  role text,
  is_primary boolean not null default false,
  created_at bigint not null
);

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  subject text not null,
  body text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.email_messages (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint references public.companies(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  template_id bigint references public.email_templates(id) on delete set null,
  recipient text not null,
  subject text not null,
  body text not null,
  status text not null default 'QUEUED' check (status in ('QUEUED', 'SENT', 'FAILED')),
  kind text not null default 'INDIVIDUAL' check (kind in ('INDIVIDUAL', 'BATCH')),
  provider_message_id text,
  error_message text,
  sent_at bigint,
  created_at bigint not null
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint references public.companies(id) on delete cascade,
  type text not null,
  description text not null,
  created_at bigint not null
);

create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint not null references public.companies(id) on delete cascade,
  due_at bigint not null,
  status text not null default 'PENDING' check (status in ('PENDING', 'COMPLETED', 'LOCKED')),
  note text,
  created_at bigint not null
);

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  file_name text not null,
  total_rows integer not null,
  imported_rows integer not null,
  updated_rows integer not null default 0,
  skipped_rows integer not null default 0,
  error_rows integer not null default 0,
  created_at bigint not null
);

create table if not exists public.email_accounts (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  provider text not null default 'GMAIL' check (provider = 'GMAIL'),
  email text not null,
  encrypted_refresh_token text not null,
  scopes text not null default '',
  connected_at bigint not null,
  updated_at bigint not null,
  constraint uq_email_accounts_owner_provider unique (owner_id, provider)
);

create table if not exists public.oauth_states (
  state text primary key,
  owner_id text not null,
  expires_at bigint not null,
  created_at bigint not null
);

create table if not exists public.crm_settings (
  owner_id text primary key,
  sender_name text not null default '',
  signature text not null default '',
  daily_send_limit integer not null default 100,
  timezone text not null default 'America/Sao_Paulo',
  updated_at bigint not null
);

create index if not exists idx_companies_owner_status on public.companies(owner_id, status);
create index if not exists idx_companies_owner_region_city on public.companies(owner_id, region, city);
create index if not exists idx_companies_owner_email on public.companies(owner_id, primary_email);
create index if not exists idx_contacts_company on public.contacts(company_id);
create index if not exists idx_email_templates_owner_updated on public.email_templates(owner_id, updated_at desc);
create index if not exists idx_email_messages_owner_created on public.email_messages(owner_id, created_at desc);
create index if not exists idx_email_messages_company on public.email_messages(company_id);
create index if not exists idx_email_messages_contact on public.email_messages(contact_id);
create index if not exists idx_activity_owner_created on public.activity_logs(owner_id, created_at desc);
create index if not exists idx_followups_owner_due on public.follow_ups(owner_id, due_at);
create index if not exists idx_followups_company on public.follow_ups(company_id);
create index if not exists idx_import_batches_owner_created on public.import_batches(owner_id, created_at desc);
create index if not exists idx_oauth_states_expires on public.oauth_states(expires_at);

alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.email_templates enable row level security;
alter table public.email_messages enable row level security;
alter table public.activity_logs enable row level security;
alter table public.follow_ups enable row level security;
alter table public.import_batches enable row level security;
alter table public.email_accounts enable row level security;
alter table public.oauth_states enable row level security;
alter table public.crm_settings enable row level security;

-- The application uses the server-side Supabase service-role key.
-- No public policies are created intentionally; never expose that key in the browser.
-- Additive migration; run before deploying the new application.
begin;
create table if not exists public.template_attachments (
  id text primary key,
  owner_id text not null,
  template_id bigint references public.email_templates(id) on delete set null,
  name text not null,
  mime_type text not null,
  size integer not null check (size > 0),
  storage_key text not null unique,
  ready boolean not null default false,
  created_at bigint not null,
  expires_at bigint not null
);
create index if not exists idx_template_attachments_owner_template on public.template_attachments(owner_id, template_id);
create index if not exists idx_template_attachments_expiry on public.template_attachments(expires_at) where template_id is null;
alter table public.template_attachments enable row level security;
alter table public.email_messages add column if not exists attachments jsonb not null default '[]'::jsonb;
commit;

-- Campanhas persistentes de e-mail.
-- Migração aditiva: não altera o comportamento do envio em lote legado.
begin;

create table if not exists public.email_campaigns (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  template_id bigint references public.email_templates(id) on delete set null,
  status text not null default 'DRAFT' check (status in ('DRAFT','READY','RUNNING','PAUSED','COMPLETED','CANCELLED')),
  audience jsonb not null default '{}'::jsonb,
  total integer not null default 0 check (total >= 0),
  pending integer not null default 0 check (pending >= 0),
  sent integer not null default 0 check (sent >= 0),
  failed integer not null default 0 check (failed >= 0),
  skipped integer not null default 0 check (skipped >= 0),
  batch_size integer not null default 25 check (batch_size between 1 and 100),
  interval_minutes integer not null default 10 check (interval_minutes >= 1),
  next_run_at bigint,
  lock_until bigint,
  started_at bigint,
  completed_at bigint,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.email_campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  recipient text not null,
  company_name text not null,
  personalization jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','SENT','FAILED','SKIPPED')),
  attempts integer not null default 0 check (attempts >= 0),
  processing_started_at bigint,
  message_id bigint,
  error_message text,
  provider_message_id text,
  sent_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  constraint uq_campaign_recipient_company unique (campaign_id, company_id)
);

-- Mantém bancos que já executaram uma versão anterior desta migration
-- compatíveis com o schema atual da aplicação.
alter table public.email_campaign_recipients add column if not exists processing_started_at bigint;
alter table public.email_campaign_recipients add column if not exists message_id bigint;

alter table public.email_messages add column if not exists campaign_id bigint references public.email_campaigns(id) on delete set null;
create index if not exists idx_email_campaigns_owner_created on public.email_campaigns(owner_id, created_at desc);
create index if not exists idx_email_campaigns_owner_status on public.email_campaigns(owner_id, status);
create index if not exists idx_email_campaigns_due on public.email_campaigns(status, next_run_at);
create index if not exists idx_campaign_recipients_campaign_status on public.email_campaign_recipients(campaign_id, status);
create index if not exists idx_campaign_recipients_processing on public.email_campaign_recipients(status, processing_started_at);
create index if not exists idx_email_messages_campaign on public.email_messages(campaign_id);
alter table public.email_campaigns enable row level security;
alter table public.email_campaign_recipients enable row level security;
commit;

﻿-- Apply BEFORE the application deployment. Existing QUEUED messages remain ambiguous.
begin;
alter table public.email_campaigns add column if not exists logical_batch jsonb;
alter table public.email_campaigns add column if not exists processing_notice text;
alter table public.email_campaign_recipients add column if not exists last_batch_id text;
alter table public.email_campaign_recipients add column if not exists failure_category text;
create table if not exists public.campaign_owner_leases (
  owner_id text primary key,
  token text not null,
  expires_at bigint not null
);
alter table public.campaign_owner_leases enable row level security;
create index if not exists idx_campaign_recipient_recovery
  on public.email_campaign_recipients (campaign_id, status, processing_started_at);
commit;

ALTER TABLE email_accounts ADD COLUMN IF NOT EXISTS needs_reconnect boolean NOT NULL DEFAULT false;

-- Extend the message lifecycle required by the campaign send barrier.
-- Does not change campaign state, recipient attempts or existing messages.
BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE public.email_messages
  DROP CONSTRAINT IF EXISTS email_messages_status_check;
ALTER TABLE public.email_messages
  ADD CONSTRAINT email_messages_status_check
  CHECK (status IN ('QUEUED', 'PREPARED', 'SENDING', 'RETRYABLE', 'UNCERTAIN', 'SENT', 'FAILED'));
COMMIT;

-- Additive; apply before deploying. All timestamps use epoch milliseconds.
begin;
set local lock_timeout = '5s';
alter table public.companies
  add column if not exists primary_email_status text not null default 'UNKNOWN',
  add column if not exists primary_email_status_reason text,
  add column if not exists primary_email_status_updated_at bigint;
alter table public.email_messages
  add column if not exists rfc_message_id text,
  add column if not exists email_account_id integer,
  add column if not exists sender_address text;
create index if not exists idx_delivery_message_reference on public.email_messages(owner_id, rfc_message_id);
create index if not exists idx_delivery_message_recipient on public.email_messages(owner_id, lower(btrim(recipient)), sent_at);
alter table public.email_campaigns
  add column if not exists delivery_monitoring_enabled boolean not null default false,
  add column if not exists delivery_next_check_at bigint,
  add column if not exists delivery_checked_at bigint,
  add column if not exists delivery_completed_at bigint,
  add column if not exists audience_without_email integer not null default 0,
  add column if not exists audience_invalid_email integer not null default 0;
-- Existing campaigns are opt-out: no unbounded historical backfill.
alter table public.email_campaigns alter column delivery_monitoring_enabled set default true;
alter table public.email_campaign_recipients
  add column if not exists delivery_status text not null default 'PENDING',
  add column if not exists delivery_failure_category text,
  add column if not exists delivery_diagnostic_code text,
  add column if not exists delivery_error_message text,
  add column if not exists bounced_at bigint,
  add column if not exists bounce_message_id text,
  add column if not exists delivery_checked_at bigint;
create table if not exists public.email_delivery_events (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
  campaign_recipient_id bigint not null references public.email_campaign_recipients(id) on delete cascade,
  email_message_id bigint not null references public.email_messages(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  recipient text not null, gmail_message_id text not null, gmail_thread_id text,
  event_type text not null, category text not null, smtp_status text, diagnostic text,
  detected_at bigint not null, created_at bigint not null
);
create unique index if not exists uq_delivery_event_message_recipient on public.email_delivery_events(owner_id, gmail_message_id, recipient);
create index if not exists idx_delivery_events_campaign on public.email_delivery_events(owner_id, campaign_id);
create table if not exists public.gmail_delivery_sync_state (
  campaign_id bigint primary key references public.email_campaigns(id) on delete cascade,
  owner_id text not null,
  email_account_id bigint not null references public.email_accounts(id) on delete cascade,
  account_connected_at bigint not null,
  last_checked_at bigint, scan_after bigint, scan_before bigint, page_token text,
  lock_token text, lock_until bigint, last_error text,
  incomplete boolean not null default false, updated_at bigint not null
);
create index if not exists idx_delivery_sync_owner_account on public.gmail_delivery_sync_state(owner_id, email_account_id);
create index if not exists idx_campaign_delivery_due on public.email_campaigns(delivery_next_check_at, completed_at)
  where delivery_monitoring_enabled and delivery_completed_at is null and status = 'COMPLETED';
create index if not exists idx_companies_owner_email_status on public.companies(owner_id, primary_email_status);
alter table public.email_delivery_events enable row level security;
alter table public.gmail_delivery_sync_state enable row level security;
-- Also protects imports and concurrent address corrections outside the PATCH route.
create or replace function public.reset_primary_email_delivery_status() returns trigger language plpgsql as $$
begin
  if lower(btrim(coalesce(new.primary_email, ''))) is distinct from lower(btrim(coalesce(old.primary_email, ''))) then
    new.primary_email_status := 'UNKNOWN';
    new.primary_email_status_reason := null;
    new.primary_email_status_updated_at := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  end if;
  return new;
end;
$$;
drop trigger if exists reset_primary_email_delivery_status on public.companies;
create trigger reset_primary_email_delivery_status before update of primary_email on public.companies
  for each row execute function public.reset_primary_email_delivery_status();
commit;

-- Recipient review state introduced by the bounded runner.
alter table public.email_campaign_recipients drop constraint if exists email_campaign_recipients_status_check;
alter table public.email_campaign_recipients add constraint email_campaign_recipients_status_check check (status in ('PENDING','PROCESSING','UNCERTAIN','SENT','FAILED','SKIPPED'));
