-- Prospecta CRM - schema for Supabase PostgreSQL
-- Run this file once in the Supabase SQL Editor.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  trade_name text,
  cnpj text,
  website text,
  segment text,
  region integer,
  city text,
  state text,
  address text,
  phone text,
  phone_whatsapp_status text not null default 'UNKNOWN' check (phone_whatsapp_status in ('UNKNOWN', 'YES', 'NO')),
  mobile text,
  mobile_whatsapp_status text not null default 'UNKNOWN' check (mobile_whatsapp_status in ('UNKNOWN', 'YES', 'NO')),
  primary_email text,
  employee_count integer,
  employee_range text,
  company_size text,
  notes text,
  status text not null default 'NOT_CONTACTED' check (status in ('NOT_CONTACTED', 'CONTACTED', 'WAITING_REPLY', 'REPLIED', 'FOLLOW_UP', 'INTERESTED', 'NOT_INTERESTED', 'CLOSED')),
  last_contact_at bigint,
  next_follow_up_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  constraint uq_companies_owner_cnpj unique (owner_id, cnpj)
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text,
  email text,
  phone text,
  role text,
  is_primary boolean not null default false,
  created_at bigint not null
);

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  subject text not null,
  body text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.email_messages (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint references public.companies(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  template_id bigint references public.email_templates(id) on delete set null,
  recipient text not null,
  subject text not null,
  body text not null,
  status text not null default 'QUEUED' check (status in ('QUEUED', 'SENT', 'FAILED')),
  kind text not null default 'INDIVIDUAL' check (kind in ('INDIVIDUAL', 'BATCH')),
  provider_message_id text,
  error_message text,
  sent_at bigint,
  created_at bigint not null
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint references public.companies(id) on delete cascade,
  type text not null,
  description text not null,
  created_at bigint not null
);

create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  company_id bigint not null references public.companies(id) on delete cascade,
  due_at bigint not null,
  status text not null default 'PENDING' check (status in ('PENDING', 'COMPLETED', 'LOCKED')),
  note text,
  created_at bigint not null
);

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  file_name text not null,
  total_rows integer not null,
  imported_rows integer not null,
  updated_rows integer not null default 0,
  skipped_rows integer not null default 0,
  error_rows integer not null default 0,
  created_at bigint not null
);

create table if not exists public.email_accounts (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  provider text not null default 'GMAIL' check (provider = 'GMAIL'),
  email text not null,
  encrypted_refresh_token text not null,
  scopes text not null default '',
  connected_at bigint not null,
  updated_at bigint not null,
  constraint uq_email_accounts_owner_provider unique (owner_id, provider)
);

create table if not exists public.oauth_states (
  state text primary key,
  owner_id text not null,
  expires_at bigint not null,
  created_at bigint not null
);

create table if not exists public.crm_settings (
  owner_id text primary key,
  sender_name text not null default '',
  signature text not null default '',
  daily_send_limit integer not null default 100,
  timezone text not null default 'America/Sao_Paulo',
  updated_at bigint not null
);

create index if not exists idx_companies_owner_status on public.companies(owner_id, status);
create index if not exists idx_companies_owner_region_city on public.companies(owner_id, region, city);
create index if not exists idx_companies_owner_email on public.companies(owner_id, primary_email);
create index if not exists idx_contacts_company on public.contacts(company_id);
create index if not exists idx_email_templates_owner_updated on public.email_templates(owner_id, updated_at desc);
create index if not exists idx_email_messages_owner_created on public.email_messages(owner_id, created_at desc);
create index if not exists idx_email_messages_company on public.email_messages(company_id);
create index if not exists idx_email_messages_contact on public.email_messages(contact_id);
create index if not exists idx_activity_owner_created on public.activity_logs(owner_id, created_at desc);
create index if not exists idx_followups_owner_due on public.follow_ups(owner_id, due_at);
create index if not exists idx_followups_company on public.follow_ups(company_id);
create index if not exists idx_import_batches_owner_created on public.import_batches(owner_id, created_at desc);
create index if not exists idx_oauth_states_expires on public.oauth_states(expires_at);

alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.email_templates enable row level security;
alter table public.email_messages enable row level security;
alter table public.activity_logs enable row level security;
alter table public.follow_ups enable row level security;
alter table public.import_batches enable row level security;
alter table public.email_accounts enable row level security;
alter table public.oauth_states enable row level security;
alter table public.crm_settings enable row level security;

-- The application uses the server-side Supabase service-role key.
-- No public policies are created intentionally; never expose that key in the browser.