"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Edit3, Mail, Phone, Plus, Search, Star, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Company={id:number;name:string};
type Contact={id:number;companyId:number;companyName:string;name?:string|null;email?:string|null;phone?:string|null;role?:string|null;isPrimary:boolean;createdAt:string};
const empty={companyId:"",name:"",email:"",phone:"",role:"",isPrimary:false};

export function ContactsPage(){
 const[contacts,setContacts]=useState<Contact[]>([]),[companies,setCompanies]=useState<Company[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Contact|null>(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const[c,p]=await Promise.all([fetch(`/api/contacts?search=${encodeURIComponent(search)}`),fetch("/api/companies")]);if(!c.ok||!p.ok)throw new Error();setContacts(await c.json());setCompanies(await p.json())}catch{toast.error("Não foi possível carregar os contatos.")}},[search]);useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer)},[load]);
 const primaryCount=useMemo(()=>contacts.filter(c=>c.isPrimary).length,[contacts]);
 function startNew(){setEditing(null);setForm(empty);setOpen(true)} function startEdit(contact:Contact){setEditing(contact);setForm({companyId:String(contact.companyId),name:contact.name||"",email:contact.email||"",phone:contact.phone||"",role:contact.role||"",isPrimary:contact.isPrimary});setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const companyId=Number(form.companyId),response=await fetch(`/api/companies/${companyId}/contacts`,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editing?.id})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Falha ao salvar contato.");toast.success(editing?"Contato atualizado.":"Contato adicionado.");setOpen(false);await load()}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar.")}finally{setSaving(false)}}
 async function remove(contact:Contact){if(!confirm(`Excluir ${contact.name||contact.email}?`))return;const r=await fetch(`/api/companies/${contact.companyId}/contacts?contactId=${contact.id}`,{method:"DELETE"});if(r.ok){toast.success("Contato excluído.");await load()}else toast.error("Não foi possível excluir.")}
 return <><section className="page-intro compact"><div><p className="eyebrow">REDE DE CONTATOS</p><h1>Contatos</h1><p>Encontre as pessoas certas em todas as empresas da sua base.</p></div><Button onClick={startNew}><Plus/>Novo contato</Button></section><section className="contact-metrics"><article><UserRound/><div><span>Total de contatos</span><strong>{contacts.length}</strong></div></article><article><Star/><div><span>Contatos principais</span><strong>{primaryCount}</strong></div></article><article><Building2/><div><span>Empresas representadas</span><strong>{new Set(contacts.map(c=>c.companyId)).size}</strong></div></article></section><section className="panel contacts-hub"><div className="contacts-toolbar"><div className="search"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, empresa, cargo ou e-mail"/></div></div>{contacts.length?<div className="contacts-table"><table><thead><tr><th>Contato</th><th>Empresa</th><th>Cargo</th><th>Comunicação</th><th></th></tr></thead><tbody>{contacts.map(contact=><tr key={contact.id}><td><div className="hub-person"><span>{(contact.name||contact.email||"C").slice(0,2).toUpperCase()}</span><div><strong>{contact.name||"Sem nome"}{contact.isPrimary?<em><Star/>Principal</em>:null}</strong><small>{contact.email||"E-mail não informado"}</small></div></div></td><td><span className="hub-company"><Building2/>{contact.companyName}</span></td><td>{contact.role||"—"}</td><td><div className="hub-lines">{contact.email?<a href={`mailto:${contact.email}`}><Mail/>{contact.email}</a>:null}{contact.phone?<span><Phone/>{contact.phone}</span>:null}</div></td><td><div className="hub-actions"><button onClick={()=>startEdit(contact)} aria-label={`Editar ${contact.name||"contato"}`}><Edit3/></button><button onClick={()=>remove(contact)} aria-label={`Excluir ${contact.name||"contato"}`}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<div className="contacts-empty"><UserRound/><h2>{search?"Nenhum contato encontrado":"Nenhum contato cadastrado"}</h2><p>{search?"Tente outro termo de busca.":"Adicione uma pessoa e vincule-a a uma empresa."}</p>{!search?<Button onClick={startNew}><Plus/>Adicionar primeiro contato</Button>:null}</div>}</section><ContactEditor open={open} setOpen={setOpen} editing={editing} companies={companies} form={form} setForm={setForm} saving={saving} save={save}/></>;
}

function ContactEditor({open,setOpen,editing,companies,form,setForm,saving,save}:{open:boolean;setOpen:(v:boolean)=>void;editing:Contact|null;companies:Company[];form:typeof empty;setForm:React.Dispatch<React.SetStateAction<typeof empty>>;saving:boolean;save:(e:React.FormEvent)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{editing?"Editar contato":"Novo contato"}</DialogTitle><DialogDescription>Cadastre os dados da pessoa e a empresa onde ela trabalha.</DialogDescription></DialogHeader><div className="contact-editor-grid"><div className="field wide"><Label>Empresa *</Label><Select value={form.companyId} onValueChange={companyId=>setForm(v=>({...v,companyId}))} disabled={Boolean(editing)}><SelectTrigger><SelectValue placeholder="Selecione uma empresa"/></SelectTrigger><SelectContent>{companies.map(company=><SelectItem key={company.id} value={String(company.id)}>{company.name}</SelectItem>)}</SelectContent></Select></div><div className="field"><Label htmlFor="contact-name">Nome</Label><Input id="contact-name" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Nome da pessoa"/></div><div className="field"><Label htmlFor="contact-role">Cargo</Label><Input id="contact-role" value={form.role} onChange={e=>setForm(v=>({...v,role:e.target.value}))} placeholder="Ex.: Gerente comercial"/></div><div className="field"><Label htmlFor="contact-email">E-mail</Label><Input id="contact-email" type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} placeholder="nome@empresa.com"/></div><div className="field"><Label htmlFor="contact-phone">Telefone</Label><Input id="contact-phone" value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} placeholder="(11) 99999-9999"/></div><label className="primary-choice"><Checkbox checked={form.isPrimary} onCheckedChange={value=>setForm(v=>({...v,isPrimary:Boolean(value)}))}/><span><strong>Contato principal</strong><small>Será priorizado nos envios para esta empresa.</small></span></label></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving||!form.companyId||(!form.name.trim()&&!form.email.trim())}>{saving?"Salvando…":"Salvar contato"}</Button></DialogFooter></form></DialogContent></Dialog>}
