"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CalendarClock, Check, CheckCircle2, Clock3, Plus, RotateCcw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Company={id:number;name:string};
type FollowUp={id:number;companyId:number;companyName:string;dueAt:string;status:string;note?:string|null;createdAt:string};

export function FollowUpsPage(){
 const[items,setItems]=useState<FollowUp[]>([]),[companies,setCompanies]=useState<Company[]>([]),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[companyId,setCompanyId]=useState(""),[dueAt,setDueAt]=useState(""),[note,setNote]=useState("");
 const load=useCallback(async()=>{try{const[f,c]=await Promise.all([fetch("/api/followups"),fetch("/api/companies")]);if(!f.ok||!c.ok)throw new Error();setItems(await f.json());setCompanies(await c.json())}catch{toast.error("Não foi possível carregar os follow-ups.")}},[]); useEffect(()=>{void load()},[load]);
 const now=new Date(),todayStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),tomorrow=todayStart+86400000;
 const pending=items.filter(i=>i.status==="PENDING"),overdue=pending.filter(i=>new Date(i.dueAt).getTime()<todayStart),today=pending.filter(i=>{const d=new Date(i.dueAt).getTime();return d>=todayStart&&d<tomorrow}),upcoming=pending.filter(i=>new Date(i.dueAt).getTime()>=tomorrow),completed=items.filter(i=>i.status==="COMPLETED").slice(-10).reverse();
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/followups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({companyId:Number(companyId),dueAt,note})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||"Falha ao agendar.");toast.success("Follow-up agendado.");setOpen(false);setCompanyId("");setDueAt("");setNote("");await load()}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível agendar.")}finally{setSaving(false)}}
 async function update(id:number,status:string){const r=await fetch("/api/followups",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(r.ok){toast.success(status==="COMPLETED"?"Follow-up concluído.":"Follow-up reaberto.");await load()}else toast.error("Não foi possível atualizar.")}
 async function remove(id:number){if(!confirm("Excluir este follow-up?"))return;const r=await fetch(`/api/followups?id=${id}`,{method:"DELETE"});if(r.ok){toast.success("Follow-up excluído.");await load()}else toast.error("Não foi possível excluir.")}
 return <><section className="page-intro compact"><div><p className="eyebrow">ACOMPANHAMENTO COMERCIAL</p><h1>Follow-ups</h1><p>Organize os próximos contatos e não deixe oportunidades esquecidas.</p></div><FollowUpDialog open={open} setOpen={setOpen} companies={companies} companyId={companyId} setCompanyId={setCompanyId} dueAt={dueAt} setDueAt={setDueAt} note={note} setNote={setNote} saving={saving} create={create}/></section><section className="follow-metrics"><article><AlertCircle/><div><span>Atrasados</span><strong>{overdue.length}</strong></div></article><article><CalendarClock/><div><span>Para hoje</span><strong>{today.length}</strong></div></article><article><Clock3/><div><span>Próximos</span><strong>{upcoming.length}</strong></div></article><article><CheckCircle2/><div><span>Concluídos</span><strong>{items.filter(i=>i.status==="COMPLETED").length}</strong></div></article></section><section className="follow-grid"><FollowColumn title="Atrasados" subtitle="Precisam de atenção" items={overdue} tone="late" onComplete={id=>update(id,"COMPLETED")} onDelete={remove}/><FollowColumn title="Hoje" subtitle="Contatos programados" items={today} tone="today" onComplete={id=>update(id,"COMPLETED")} onDelete={remove}/><FollowColumn title="Próximos" subtitle="Agenda futura" items={upcoming} tone="next" onComplete={id=>update(id,"COMPLETED")} onDelete={remove}/></section>{completed.length?<section className="panel completed-follows"><div className="panel-heading"><div><h2>Concluídos recentemente</h2><p>Últimos acompanhamentos finalizados</p></div><CheckCircle2/></div>{completed.map(item=><article key={item.id}><div><strong>{item.companyName}</strong><span>{item.note||"Follow-up sem observação"}</span></div><small>{new Date(item.dueAt).toLocaleString("pt-BR")}</small><button onClick={()=>update(item.id,"PENDING")}><RotateCcw/>Reabrir</button></article>)}</section>:null}</>;
}

function FollowUpDialog({open,setOpen,companies,companyId,setCompanyId,dueAt,setDueAt,note,setNote,saving,create}:{open:boolean;setOpen:(v:boolean)=>void;companies:Company[];companyId:string;setCompanyId:(v:string)=>void;dueAt:string;setDueAt:(v:string)=>void;note:string;setNote:(v:string)=>void;saving:boolean;create:(e:React.FormEvent)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>Novo follow-up</Button></DialogTrigger><DialogContent><form onSubmit={create}><DialogHeader><DialogTitle>Agendar follow-up</DialogTitle><DialogDescription>Defina quando você pretende retomar o contato com a empresa.</DialogDescription></DialogHeader><div className="follow-form"><div className="field"><Label>Empresa *</Label><Select value={companyId} onValueChange={setCompanyId}><SelectTrigger><SelectValue placeholder="Selecione uma empresa"/></SelectTrigger><SelectContent>{companies.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></div><div className="field"><Label htmlFor="follow-date">Data e horário *</Label><Input id="follow-date" type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)} required/></div><div className="field"><Label htmlFor="follow-note">Observação</Label><Textarea id="follow-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: confirmar se recebeu a proposta" maxLength={500}/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving||!companyId||!dueAt}>{saving?"Agendando…":"Agendar"}</Button></DialogFooter></form></DialogContent></Dialog>}
function FollowColumn({title,subtitle,items,tone,onComplete,onDelete}:{title:string;subtitle:string;items:FollowUp[];tone:string;onComplete:(id:number)=>void;onDelete:(id:number)=>void}){return <article className={`panel follow-column ${tone}`}><header><div><h2>{title}</h2><p>{subtitle}</p></div><span>{items.length}</span></header><div>{items.length?items.map(item=><section key={item.id} className="follow-card"><div className="follow-date"><CalendarClock/><span>{new Date(item.dueAt).toLocaleDateString("pt-BR")}</span><strong>{new Date(item.dueAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</strong></div><h3>{item.companyName}</h3><p>{item.note||"Sem observação adicionada."}</p><footer><Button size="sm" onClick={()=>onComplete(item.id)}><Check/>Concluir</Button><button onClick={()=>onDelete(item.id)} aria-label={`Excluir follow-up de ${item.companyName}`}><Trash2/></button></footer></section>):<div className="follow-empty"><CheckCircle2/><span>Nenhum follow-up aqui</span></div>}</div></article>}
