"use client";

import { useEffect, useState } from "react";
import { Building2, CheckCircle2, Clock3, MailCheck, Pause, Play, RefreshCw, RotateCcw, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

export type CampaignMonitorData={id:number;name:string;status:string;total?:number;pending?:number;sent?:number;failed?:number;skipped?:number;batchSize?:number;intervalMinutes?:number;nextRunAt?:string|null};

export function CampaignMonitor({initialCampaign}:{initialCampaign:CampaignMonitorData}){
 const[campaign,setCampaign]=useState(initialCampaign),[controlling,setControlling]=useState(false);
 useEffect(()=>{if(!["READY","RUNNING","PAUSED"].includes(campaign.status))return;const timer=setInterval(()=>{void fetch("/api/email-campaigns").then(async response=>{if(!response.ok)return;const rows=await response.json() as CampaignMonitorData[];const fresh=rows.find(item=>item.id===campaign.id);if(fresh)setCampaign(fresh)}).catch(()=>undefined)},5000);return()=>clearInterval(timer)},[campaign.id,campaign.status]);
 async function control(action:"start"|"pause"|"resume"){setControlling(true);try{const response=await fetch(`/api/email-campaigns/${campaign.id}/control`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json() as CampaignMonitorData&{error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível alterar a campanha.");setCampaign(data);toast.success(action==="start"?"Campanha iniciada.":action==="pause"?"Campanha pausada.":"Campanha retomada.")}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível alterar a campanha.")}finally{setControlling(false)}}
 const total=campaign.total||0,sent=campaign.sent||0,failed=campaign.failed||0,skipped=campaign.skipped||0,pending=campaign.pending||0,finished=sent+failed+skipped,progress=total?Math.min(100,Math.round(finished/total*100)):0;
 const title=campaign.status==="READY"?"Pronta para iniciar":campaign.status==="RUNNING"?"Campanha em execução":campaign.status==="PAUSED"?"Campanha pausada":"Campanha concluída";
 return <><section className="page-intro compact"><div><p className="eyebrow">CAMPANHA</p><h1>{campaign.name}</h1><p>Acompanhe o processamento sem precisar manter esta página aberta.</p></div></section><section className="panel batch-results"><div className="panel-heading"><div><h2>{title}</h2><p>{progress}% processado · {pending} pendentes</p></div>{campaign.status==="RUNNING"?<RefreshCw className="spin"/>:<CheckCircle2/>}</div><div className="batch-preview"><span>PROGRESSO</span><h3>{finished} de {total} processados</h3><div className="campaign-progress-track"><div className="campaign-progress-value" style={{width:`${progress}%`}}/></div><div className="campaign-audience-stats"><span><MailCheck/><strong>{sent}</strong> enviados</span><span><Clock3/><strong>{pending}</strong> pendentes</span><span><Users/><strong>{skipped}</strong> ignorados</span><span><Building2/><strong>{failed}</strong> falhas</span></div></div><div className="batch-warning"><Clock3/><span>Pacotes de {campaign.batchSize||25} mensagens a cada {campaign.intervalMinutes||10} minutos.{campaign.nextRunAt?` Próxima execução: ${new Date(campaign.nextRunAt).toLocaleString("pt-BR")}.`:""}</span></div><div className="campaign-controls">{campaign.status==="READY"&&<Button disabled={controlling} onClick={()=>control("start")}><Play/>Iniciar campanha</Button>}{campaign.status==="RUNNING"&&<Button variant="outline" disabled={controlling} onClick={()=>control("pause")}><Pause/>Pausar campanha</Button>}{campaign.status==="PAUSED"&&<Button disabled={controlling} onClick={()=>control("resume")}><RotateCcw/>Retomar campanha</Button>}</div></section></>;
}
