-- Campanhas persistentes de e-mail.
-- Migração aditiva: não altera o comportamento do envio em lote legado.
begin;

create table if not exists public.email_campaigns (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  template_id bigint references public.email_templates(id) on delete set null,
  status text not null default 'DRAFT' check (status in ('DRAFT','READY','RUNNING','PAUSED','COMPLETED','CANCELLED')),
  audience jsonb not null default '{}'::jsonb,
  total integer not null default 0 check (total >= 0),
  pending integer not null default 0 check (pending >= 0),
  sent integer not null default 0 check (sent >= 0),
  failed integer not null default 0 check (failed >= 0),
  skipped integer not null default 0 check (skipped >= 0),
  batch_size integer not null default 25 check (batch_size between 1 and 100),
  interval_minutes integer not null default 10 check (interval_minutes >= 1),
  started_at bigint,
  completed_at bigint,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.email_campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  recipient text not null,
  company_name text not null,
  personalization jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','SENT','FAILED','SKIPPED')),
  attempts integer not null default 0 check (attempts >= 0),
  error_message text,
  provider_message_id text,
  sent_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  constraint uq_campaign_recipient_company unique (campaign_id, company_id)
);

alter table public.email_messages add column if not exists campaign_id bigint references public.email_campaigns(id) on delete set null;

create index if not exists idx_email_campaigns_owner_created on public.email_campaigns(owner_id, created_at desc);
create index if not exists idx_email_campaigns_owner_status on public.email_campaigns(owner_id, status);
create index if not exists idx_campaign_recipients_campaign_status on public.email_campaign_recipients(campaign_id, status);
create index if not exists idx_email_messages_campaign on public.email_messages(campaign_id);

alter table public.email_campaigns enable row level security;
alter table public.email_campaign_recipients enable row level security;

-- O CRM continua acessando o banco somente pelo servidor/service-role.
-- Nenhuma policy pública é criada.
commit;
