-- Additive; apply before deploying. All timestamps use epoch milliseconds.
begin;
set local lock_timeout = '5s';
alter table public.companies
  add column if not exists primary_email_status text not null default 'UNKNOWN',
  add column if not exists primary_email_status_reason text,
  add column if not exists primary_email_status_updated_at bigint;
alter table public.email_messages
  add column if not exists rfc_message_id text,
  add column if not exists email_account_id integer,
  add column if not exists sender_address text;
create index if not exists idx_delivery_message_reference on public.email_messages(owner_id, rfc_message_id);
create index if not exists idx_delivery_message_recipient on public.email_messages(owner_id, lower(btrim(recipient)), sent_at);
alter table public.email_campaigns
  add column if not exists delivery_monitoring_enabled boolean not null default false,
  add column if not exists delivery_next_check_at bigint,
  add column if not exists delivery_checked_at bigint,
  add column if not exists delivery_completed_at bigint,
  add column if not exists audience_without_email integer not null default 0,
  add column if not exists audience_invalid_email integer not null default 0;
-- Existing campaigns are opt-out: no unbounded historical backfill.
alter table public.email_campaigns alter column delivery_monitoring_enabled set default true;
alter table public.email_campaign_recipients
  add column if not exists delivery_status text not null default 'PENDING',
  add column if not exists delivery_failure_category text,
  add column if not exists delivery_diagnostic_code text,
  add column if not exists delivery_error_message text,
  add column if not exists bounced_at bigint,
  add column if not exists bounce_message_id text,
  add column if not exists delivery_checked_at bigint;
create table if not exists public.email_delivery_events (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
  campaign_recipient_id bigint not null references public.email_campaign_recipients(id) on delete cascade,
  email_message_id bigint not null references public.email_messages(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  recipient text not null, gmail_message_id text not null, gmail_thread_id text,
  event_type text not null, category text not null, smtp_status text, diagnostic text,
  detected_at bigint not null, created_at bigint not null
);
create unique index if not exists uq_delivery_event_message_recipient on public.email_delivery_events(owner_id, gmail_message_id, recipient);
create index if not exists idx_delivery_events_campaign on public.email_delivery_events(owner_id, campaign_id);
create table if not exists public.gmail_delivery_sync_state (
  campaign_id bigint primary key references public.email_campaigns(id) on delete cascade,
  owner_id text not null,
  email_account_id bigint not null references public.email_accounts(id) on delete cascade,
  account_connected_at bigint not null,
  last_checked_at bigint, scan_after bigint, scan_before bigint, page_token text,
  lock_token text, lock_until bigint, last_error text,
  incomplete boolean not null default false, updated_at bigint not null
);
create index if not exists idx_delivery_sync_owner_account on public.gmail_delivery_sync_state(owner_id, email_account_id);
create index if not exists idx_campaign_delivery_due on public.email_campaigns(delivery_next_check_at, completed_at)
  where delivery_monitoring_enabled and delivery_completed_at is null and status = 'COMPLETED';
create index if not exists idx_companies_owner_email_status on public.companies(owner_id, primary_email_status);
alter table public.email_delivery_events enable row level security;
alter table public.gmail_delivery_sync_state enable row level security;
-- Also protects imports and concurrent address corrections outside the PATCH route.
create or replace function public.reset_primary_email_delivery_status() returns trigger language plpgsql as $$
begin
  if lower(btrim(coalesce(new.primary_email, ''))) is distinct from lower(btrim(coalesce(old.primary_email, ''))) then
    new.primary_email_status := 'UNKNOWN';
    new.primary_email_status_reason := null;
    new.primary_email_status_updated_at := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  end if;
  return new;
end;
$$;
drop trigger if exists reset_primary_email_delivery_status on public.companies;
create trigger reset_primary_email_delivery_status before update of primary_email on public.companies
  for each row execute function public.reset_primary_email_delivery_status();
commit;
