-- Apply after existing migrations. No production execution by the development agent.
begin;
set local lock_timeout = '5s';
alter table public.email_messages drop constraint if exists email_messages_kind_check;
alter table public.email_messages add constraint email_messages_kind_check check (kind in ('INDIVIDUAL', 'BATCH', 'SMART'));
create table public.document_send_batches (
 id bigint generated by default as identity primary key, owner_id text not null, name text not null,
 status text not null default 'DRAFT' check (status in ('DRAFT','READY','RUNNING','PAUSED','COMPLETED','CANCELLED')),
 revision integer not null default 0, template_id bigint references public.email_templates(id) on delete set null, template_name text, sender_address text, account_id bigint references public.email_accounts(id) on delete set null,
 common_attachments jsonb not null default '[]', interval_seconds integer not null default 60 check (interval_seconds between 1 and 3600),
 next_run_at bigint, lock_token text, lock_until bigint, notice text, confirmed_at bigint, completed_at bigint,
 created_at bigint not null, updated_at bigint not null, unique (owner_id, id)
);
create table public.document_send_items (
 id text primary key, owner_id text not null, batch_id bigint not null references public.document_send_batches(id),
 file_name text not null, file_size integer not null check (file_size between 1 and 8388608), content_hash text not null,
 storage_key text not null unique, file_ready boolean not null default false, readable boolean not null default false,
 removed_at bigint, file_deleted_at bigint, duplicate_of text references public.document_send_items(id),
 company_id bigint references public.companies(id) on delete set null, company_name text, company_cnpj text, recipient text,
 extracted_cnpjs jsonb not null default '[]', candidates jsonb not null default '[]',
 identification_method text not null default 'MANUAL', review_status text not null default 'UPLOADING',
 confirmed_at bigint, excluded boolean not null default false, subject text, body text,
 send_status text not null default 'DRAFT' check (send_status in ('DRAFT','PENDING','PROCESSING','SENT','FAILED','SKIPPED','UNCERTAIN')),
 attempts integer not null default 0, infrastructure_attempts integer not null default 0,
 message_id bigint references public.email_messages(id) on delete set null, rfc_message_id text not null unique, provider_message_id text,
 processing_at bigint, sent_at bigint, error text,
 delivery_status text not null default 'PENDING', delivery_error text, bounce_message_id text,
 delivery_checked_at bigint, delivery_next_at bigint, delivery_page_token text, delivery_before bigint, delivery_incomplete boolean not null default false,
 delivery_lock_token text, delivery_lock_until bigint,
 created_at bigint not null, updated_at bigint not null,
 foreign key (owner_id, batch_id) references public.document_send_batches(owner_id, id)
);
create index idx_document_batches_due on public.document_send_batches(status, next_run_at);
create index idx_document_batches_owner on public.document_send_batches(owner_id, created_at);
create index idx_document_items_batch on public.document_send_items(owner_id, batch_id);
create index idx_document_items_hash on public.document_send_items(owner_id, content_hash);
create index idx_document_items_delivery on public.document_send_items(send_status, delivery_next_at);
alter table public.document_send_batches enable row level security;
alter table public.document_send_items enable row level security;
create table public.document_send_delivery_events (
 id bigint generated by default as identity primary key, item_id text not null references public.document_send_items(id), owner_id text not null,
 gmail_message_id text not null, status text not null, category text not null, diagnostic text, created_at bigint not null,
 constraint uq_smart_delivery_event unique (item_id, gmail_message_id)
);
alter table public.document_send_delivery_events enable row level security;
revoke all on public.document_send_delivery_events from anon, authenticated;
-- Access only via authenticated server APIs; no anonymous/authenticated PostgREST policies.
revoke all on public.document_send_batches, public.document_send_items from anon, authenticated;
-- Names, CNPJ, recipient and message snapshots survive source deletion.
-- Foreign keys clear deleted live references; ownership is rechecked on every operation.
commit;
